# .github/workflows/build_android.yml

# name: Flutter Build APK & IPA
name: Deploy on Play Store

on:
  push:
    branches:
      - main
      # - development

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2" # change to your version

      # Install dependencies
      - run: flutter pub get

      # Decode keystore from secret
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          cat > android/key.properties <<EOL
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOL

      # Build signed App Bundle
      - run: flutter build appbundle --release

 # Upload AAB artifact so deploy job can use it
      - uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  deploy-android:
    name: Deploy Android App to Play Store
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

 # Download the .aab from build job
      - uses: actions/download-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/

      # Deploy to Play Store
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          packageName: com.otobix.auctionapp
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal   # can be internal, alpha, beta, production
          status: completed

  # build-ios:
  #   name: Build iOS IPA
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Flutter
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "3.35.2"

  #     - name: Install dependencies
  #       run: flutter pub get

  #     # Build iOS IPA (no signing yet, just simulator build)
  #     - name: Build iOS (no codesign)
  #       run: flutter build ios --release --no-codesign

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: ios-ipa
  #         path: build/ios/iphoneos

  # deploy-ios:
  #   name: Deploy iOS to TestFlight
  #   needs: build-ios
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: ios-ipa
  #         path: build/ios/iphoneos

  #     # Install fastlane
  #     - name: Setup Fastlane
  #       run: sudo gem install fastlane -NV

  #     # Upload to TestFlight
  #     - name: Upload to TestFlight
  #       env:
  #         APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
  #         APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
  #         APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APPSTORE_KEY_CONTENT }}
  #       run: |
  #         cd ios
  #         fastlane pilot upload \
  #           --api_key_path <(echo "{\"key_id\":\"$APP_STORE_CONNECT_API_KEY_ID\",\"issuer_id\":\"$APP_STORE_CONNECT_ISSUER_ID\",\"key\":\"$APP_STORE_CONNECT_KEY_CONTENT\",\"in_house\":false}") \
  #           --ipa ../build/ios/iphoneos/Runner.ipa
