name: Flutter Build APK & IPA

on:
  push:
    branches:
      - main
      - development

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2" # change to your version

      # Install dependencies
      - run: flutter pub get

      # # Build APK
      # - run: flutter build apk --release

      # # Upload APK artifact
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: android-apk-${{ github.ref_name }}
      #     path: build/app/outputs/flutter-apk/app-release.apk
      # Decode keystore from secret
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          cat > android/key.properties <<EOL
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOL

      # Build signed App Bundle
      - run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-aab-${{ github.ref_name }}
          path: build/app/outputs/bundle/release/app-release.aab

  deploy-android:
    name: Deploy Android App to Play Store
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          packageName: com.otobix.auctionapp
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal   # can be internal, alpha, beta, production
          status: completed


  # build-ios:
  #   name: Build iOS IPA
  #   runs-on: macos-latest
  #   steps:
  #     # Checkout code
  #     - uses: actions/checkout@v4

  #     # Setup Flutter
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "3.35.2"

  #     # Install dependencies
  #     - run: flutter pub get

  #     # Build iOS IPA (no signing)
  #     - run: flutter build ios --release --no-codesign

  #     # Package IPA (Xcode required step)
  #     - name: Export IPA
  #       run: |
  #         mkdir -p build/ios/ipa
  #         xcodebuild -exportArchive \
  #           -archivePath build/ios/archive/MyApp.xcarchive \
  #           -exportPath build/ios/ipa \
  #           -exportOptionsPlist ExportOptions.plist || true

  #     # Upload IPA artifact
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: ios-ipa-${{ github.ref_name }}
  #         path: build/ios/ipa
